export const UI_ACTIONS = {
  UPDATE_NAME: 'UPDATE_NAME',
  INCREMENT_COUNT: 'INCREMENT_COUNT'
};

export const FECTH_QUESTIONS = 'FECTH_QUESTIONS';
export const NEW_QUESTION = 'NEW_QUESTION';
export const NEW_ANSWER = 'NEW_ANSWER';
